#!/usr/bin/env ruby
require 'rubygems'
require "daemons"
require 'yaml'

options =  YAML::load(File.open(File.dirname(__FILE__) + "/../../config/daemons.yml"))
options = options.inject({}) do |opt, (key, value)|
    opt[(key.to_sym rescue key) || key] = value
  opt
end
options[:dir_mode] = options[:dir_mode].to_sym

Daemons.run File.dirname(__FILE__) + '/sequreispd.rb', options


