#!/bin/bash

ip=$(ifconfig $1 | grep -o "inet addr:[^ ]*" | grep -o "[0-9][^ ]*")
echo $1 $ip
#tc qdisc del root dev $1
for url in \
    http://download.xs4all.nl/test/1GB.bin \
    http://mirror.widexs.nl/ftp/pub/speed/1000mb.bin \
    http://speed.transip.nl/1000mb.bin \
    http://www.streamservice.nl/1000mb.bin \
    http://mirror.nl.leaseweb.net/speedtest/1000mb.bin \
    http://www.colocenter.nl/speedtest/1000mb.bin \
    http://speedtest.serverius.net/files/1000mb.bin \
    http://speedtest.tele2.net/1GB.zip \
    http://zgb-speedtest-1.tele2.net/1GB.zip \
    http://speedtest.reliableservers.com/1GBtest.bin \
    http://mirror.de.leaseweb.net/speedtest/1000mb.bin \
    http://ovh.net/files/1Gio.dat \
    http://speedtest.as5577.net/1000mb.bin \
    http://mirror.sfo12.us.leaseweb.net/speedtest/1000mb.bin \
    http://mirror.wdc1.us.leaseweb.net/speedtest/1000mb.bin \
    http://www.as35662.net/1000.log \
    http://speedtest.superhosting.cz/test.php?size=1G \
    http://testfiles.de.vpsnine.com/testfile_1024mb \
    http://testfiles.usnyc.vpsnine.com/testfile_1024mb \
    http://testfiles.uschi.vpsnine.com/testfile_1024mb \
    http://testfiles.nzakl.vpsnine.com/testfile_1024mb \
    http://speedtest-us-chicago.swiftway.net/1000MB.bin
do
    for times in $(seq 1 10)
    do
	wget --quiet --bind-address=$ip  -O /dev/null $url &
    done
done

iftop -i $1
killall -9 wget
