#!/usr/bin/ruby

require 'optparse'
require 'optparse/time'
require 'ostruct'
require 'pp'

options = OpenStruct.new
options.env = "production"
options.path = "/opt/sequreisp/deploy/current/"
options.cmd = ""
options.log_file = "log/production.log"

ARGV << "-h" if ARGV.empty?

opts = OptionParser.new do |opts|

  opts.banner = "Usage: sequreisp [options]"

  opts.separator ""
  opts.separator "Specific options:"

  opts.on("-a", "--apply-changes", "Apply changes. Example: sequreisp -a") do
    options.cmd = "runner"
    options.extension = "require 'sequreisp'; boot"
  end

  opts.on("-m", "--manual-apply-changes", "Manual apply changes. Example: sequreisp -m") do
    options.cmd = "runner"
    options.extension = "require 'sequreisp'; boot"
  end

  opts.on("-z", "--safe-mode", "Active safe-mode. Example: sequreisp -z.") do
    options.cmd = "runner"
    options.extension = "conf = Configuration; conf.in_safe_mode = true; conf.save"
  end

  opts.on("-n", "--no-safe-mode", "Desactive safe-mode. Example: sequreisp -n.") do
    options.cmd = "runner"
    options.extension = "conf = Configuration; conf.in_safe_mode = false; conf.save"
  end

  opts.on("-p","--providers", "Show provider status. Example: sequreisp -p") do
    options.cmd= "runner"
    options.extension ="Provider.all.map{|a| puts 'Name: ' + a.name + ', kind: ' + a.kind + ', IP: ' + a.ip + ',rate_down: ' + a.rate_down.to_s + ',rate_up: ' + a.rate_up.to_s + ', State: ' + a.state + '\n' }"
  end

  opts.on("-t", "--tail FILE", "Show tail for production, command, command_human, daemon log. Example sequreisp -t [production|command|command_human|daemon]") do |log_file|
    options.cmd = "tail"
    options.extension = "-n80 -F"
    if log_file == "daemon"
      options.path = "/"
      options.log_file = "var/log/syslog | grep [SequreISP][Daemon]"
    else
      options.log_file = "log/#{log_file}.log"
    end
  end

  opts.on("-v", "--version", "Show version app. Example: sequreisp -v") do
    options.cmd = "runner"
    options.extension = "puts 'Version: ' + Configuration.app_version"
  end

  opts.on("-c", "--console", "Open rails console. Example: sequreisp -c") do
    options.cmd = "console"
  end

  opts.on("-x", "--console-sandbox", "Open rails console in sandbox mode. WARNING you must used with option -c. Example: sequreisp -c -x.") do
    options.extension = "-x"
  end

  opts.on("-e", "--environment ENVIRONMENT", "Define environment by default use production. Example sequreisp -e [production|development|test]") do |env|
    options.env = env
    options.path = "." if env == "development"
  end

  opts.on_tail("-h", "--help", "Show this message") do
    puts opts
    exit
  end

  ##########################################################
  #
  ##########################################################
end

opts.parse!

if options.cmd
  case options.cmd
  when "tail"
    exec("#{options.cmd} #{options.extension} #{options.path}#{options.log_file}")
  when "console"
    exec("#{options.path}script/#{options.cmd} #{options.env} #{options.extension}")
  when "runner"
    exec("#{options.path}script/#{options.cmd} -e #{options.env} \"#{options.extension}\"")
  end
end
